### ISSUE TITLE
Missing iterator and __getitem__ method in EnvFile

### ISSUE THREAD

**Issue by ritterdaniel** [rafaljusiak/python-env-loader#1]
Hi @rafaljusiak,

I started using your dotenv library in a Flask project and stumbled across an issue where I tried to add all key-value pairs of an EnvFile object to a Flask app configuration.
As EnvFile is missing an iterator implementation it is not possible to do something like this:
```
app = Flask(__name__, instance_relative_config=True)
env = load_env(Path("."))
app.config.from_mapping(env)
```
Furthermore it would be cool if EnvFile would support dict-like behavior to access a value for a specific key (i.e. `env["<key>"]` ) when it isn't necessary to set a default value.

I will create a Pull request in case you are interested in adding those changes to python-env-loader.

Best regards and thanks for building such a nice and useful dotenv library!

**Comment by rafaljusiak** [comment]
Hi @dan1707, 

you are right and I like the changes you suggested. I'm glad that this small package that I created to help myself in one private project is useful to someone else :)

Thank you very much for your contribution!
